package com.focustech.oss2008.model;

/**
 * CoreCategory generated by MyEclipse Persistence Tools
 */
public class Category implements java.io.Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = -4530603176335858430L;
    // Fields
    private Long recId;
    private String catCode;
    private String parentCatCode;
    private Long catLevel;
    private String catNameEn;
    private String catNameCn;
    private String catStatus;
    private String catDescription;
    private Long catOrder;

    /**
     * @return the recId
     */
    public Long getRecId() {
        return recId;
    }

    /**
     * @param recId the recId to set
     */
    public void setRecId(Long recId) {
        this.recId = recId;
    }

    /**
     * @return the catCode
     */
    public String getCatCode() {
        return catCode;
    }

    /**
     * @param catCode the catCode to set
     */
    public void setCatCode(String catCode) {
        this.catCode = catCode;
    }

    /**
     * @return the parentCatCode
     */
    public String getParentCatCode() {
        return parentCatCode;
    }

    /**
     * @param parentCatCode the parentCatCode to set
     */
    public void setParentCatCode(String parentCatCode) {
        this.parentCatCode = parentCatCode;
    }

    /**
     * @return the catLevel
     */
    public Long getCatLevel() {
        return catLevel;
    }

    /**
     * @param catLevel the catLevel to set
     */
    public void setCatLevel(Long catLevel) {
        this.catLevel = catLevel;
    }

    /**
     * @return the catNameEn
     */
    public String getCatNameEn() {
        return catNameEn;
    }

    /**
     * @param catNameEn the catNameEn to set
     */
    public void setCatNameEn(String catNameEn) {
        this.catNameEn = catNameEn;
    }

    /**
     * @return the catNameCn
     */
    public String getCatNameCn() {
        return catNameCn;
    }

    /**
     * @param catNameCn the catNameCn to set
     */
    public void setCatNameCn(String catNameCn) {
        this.catNameCn = catNameCn;
    }

    /**
     * @return the catStatus
     */
    public String getCatStatus() {
        return catStatus;
    }

    /**
     * @param catStatus the catStatus to set
     */
    public void setCatStatus(String catStatus) {
        this.catStatus = catStatus;
    }

    /**
     * @return the catDescription
     */
    public String getCatDescription() {
        return catDescription;
    }

    /**
     * @param catDescription the catDescription to set
     */
    public void setCatDescription(String catDescription) {
        this.catDescription = catDescription;
    }

    /**
     * @return the catOrder
     */
    public Long getCatOrder() {
        return catOrder;
    }

    /**
     * @param catOrder the catOrder to set
     */
    public void setCatOrder(Long catOrder) {
        this.catOrder = catOrder;
    }

    // private String lanCode;

}
