package com.focustech.oss2008.model;

import java.util.Date;
import java.util.Set;

import com.focustech.oss2008.FieldConstants;
import com.focustech.oss2008.annotation.Display;

/**
 * OssAdminRoles generated by MyEclipse Persistence Tools
 */
public class OssAdminRole implements java.io.Serializable{
    private static final long serialVersionUID = -1383293580763208624L;
    // Fields
    private Long roleId;
    @Display(FieldConstants.ROLE_NAME_FIELD)
    private String roleName;
    private String description;
    private String active;
    private Set<OssAdminUser> users;
    private Set<RoleResource> resources;
    private String creatorId;
    private Date createdTime;
    private String modifierId;
    private Date modifiedTime;
    // Constructors
    /** default constructor */
    public OssAdminRole() {
    }

    /** minimal constructor */
    public OssAdminRole(String roleName) {
        this.roleName = roleName;
    }

    /** full constructor */
    public OssAdminRole(String roleName, String description) {
        this.roleName = roleName;
        this.description = description;
    }

    // Property accessors
    public Long getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set<OssAdminUser> getUsers() {
        return users;
    }

    public void setUsers(Set<OssAdminUser> users) {
        this.users = users;
    }

    public Set<RoleResource> getResources() {
        return resources;
    }

    public void setResources(Set<RoleResource> resources) {
        this.resources = resources;
    }

    public String getActive() {
        return active;
    }

    public void setActive(String active) {
        this.active = active;
    }

	public String getCreatorId() {
		return creatorId;
	}

	public void setCreatorId(String creatorId) {
		this.creatorId = creatorId;
	}

	public Date getCreatedTime() {
		return createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public String getModifierId() {
		return modifierId;
	}

	public void setModifierId(String modifierId) {
		this.modifierId = modifierId;
	}

	public Date getModifiedTime() {
		return modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

}
