package com.focustech.oss2008.model;

import java.util.Set;

import com.focustech.oss2008.FieldConstants;
import com.focustech.oss2008.annotation.Display;

/**
 * OssAdminResources generated by MyEclipse Persistence Tools
 */
public class OssAdminResource implements java.io.Serializable {
    private static final long serialVersionUID = -2072340548509877419L;
    // Fields
    private Long resourceId;
    @Display(FieldConstants.RESOURCE_NAME_FIELD)
    private String resourceName;
    private Long resourceParentId;
    @Display(FieldConstants.RESOURCE_TYPE_FIELD)
    private String resourceType;
    @Display(FieldConstants.RESOURCE_OPERATE_FIELD)
    private String resourceInterface;
    private String resourceDisplay;
    private String description;
    private Long resourceOrder;
    private String active;
    private String flag;
    public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	private Set<OssAdminRole> roles;

    public String getResourceInterface() {
        return resourceInterface;
    }

    public void setResourceInterface(String resourceInterface) {
        this.resourceInterface = resourceInterface;
    }

    // Property accessors
    public Long getResourceId() {
        return this.resourceId;
    }

    public void setResourceId(Long resourceId) {
        this.resourceId = resourceId;
    }

    public String getResourceName() {
        return this.resourceName;
    }

    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }

    public String getResourceType() {
        return this.resourceType;
    }

    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }

    public String getResourceDisplay() {
        return resourceDisplay;
    }

    public void setResourceDisplay(String resourceDisplay) {
        this.resourceDisplay = resourceDisplay;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set<OssAdminRole> getRoles() {
        return roles;
    }

    public void setRoles(Set<OssAdminRole> roles) {
        this.roles = roles;
    }

    public Long getResourceParentId() {
        return resourceParentId;
    }

    public void setResourceParentId(Long resourceParentId) {
        this.resourceParentId = resourceParentId;
    }

    public Long getResourceOrder() {
        return resourceOrder;
    }

    public void setResourceOrder(Long resourceOrder) {
        this.resourceOrder = resourceOrder;
    }

    public String getActive() {
        return active;
    }

    public void setActive(String active) {
        this.active = active;
    }
}
