package com.focustech.oss2008.model;

import javax.persistence.Transient;

/**
 * CrmBaseParameters generated by MyEclipse Persistence Tools
 */
public class OssAdminParameter implements java.io.Serializable {
    private static final long serialVersionUID = -2593791713609151382L;
    // Fields
    private Long recordId;
    private String parameterType;
    private String parameterName;
    private String webSite;
    private String parameterKey;
    private String parameterValue;
    private Long parameterOrder;
    private String parentParKey;
    private Integer status;
    private String isLeaf;
    // 扩展字段
    private String extend;
    @Transient
    private String parentName;
    @Transient
    private String parentValue;

    // Constructors
    /** default constructor */
    public OssAdminParameter() {
    }

    /** full constructor */
    public OssAdminParameter(String parameterType, String parameterName, String webSite, String parameterKey,
            String parameterValue, Long parameterOrder) {
        this.parameterType = parameterType;
        this.parameterName = parameterName;
        this.webSite = webSite;
        this.parameterKey = parameterKey;
        this.parameterValue = parameterValue;
        this.parameterOrder = parameterOrder;
    }

    // Property accessors
    public Long getRecordId() {
        return recordId;
    }

    public void setRecordId(Long recordId) {
        this.recordId = recordId;
    }

    public String getParameterType() {
        return parameterType;
    }

    public void setParameterType(String parameterType) {
        this.parameterType = parameterType;
    }

    public String getParameterName() {
        return parameterName;
    }

    public void setParameterName(String parameterName) {
        this.parameterName = parameterName;
    }

    public String getParameterKey() {
        return parameterKey;
    }

    public void setParameterKey(String parameterKey) {
        this.parameterKey = parameterKey;
    }

    public String getParameterValue() {
        return parameterValue;
    }

    public void setParameterValue(String parameterValue) {
        this.parameterValue = parameterValue;
    }

    public Long getParameterOrder() {
        return parameterOrder;
    }

    public void setParameterOrder(Long parameterOrder) {
        this.parameterOrder = parameterOrder;
    }

    public String getWebSite() {
        return webSite;
    }

    public void setWebSite(String webSite) {
        this.webSite = webSite;
    }

    public String getParentParKey() {
        return parentParKey;
    }

    public void setParentParKey(String parentParKey) {
        this.parentParKey = parentParKey;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getIsLeaf() {
        return isLeaf;
    }

    public void setIsLeaf(String isLeaf) {
        this.isLeaf = isLeaf;
    }

    public String getExtend() {
        return extend;
    }

    public void setExtend(String extend) {
        this.extend = extend;
    }

    public String getParentName() {
        return parentName;
    }

    public void setParentName(String parentName) {
        this.parentName = parentName;
    }

    public String getParentValue() {
        return parentValue;
    }

    public void setParentValue(String parentValue) {
        this.parentValue = parentValue;
    }

}
