package com.focustech.oss2008.model;

import java.util.Set;

import com.focustech.oss2008.FieldConstants;
import com.focustech.oss2008.annotation.Display;

/**
 * OssAdminDepartments generated by MyEclipse Persistence Tools
 */
public class OssAdminDepartment implements java.io.Serializable {
    private static final long serialVersionUID = -498623344794638319L;
    // Fields
    private String departmentId;
    @Display(FieldConstants.DEPARTMENT_NAME_FIELD)
    private String departmentName;
    private String departmentParentId;
    @Display(FieldConstants.DEPARTMENT_TYPE_FIELD)
    private String departmentType;
    private String departmentAddress;
    private String departmentContact;
    private String departmentPhone;
    private String departmentFax;
    @Display(FieldConstants.USER_ACTIVE_FIELD)
    private String active;
    private String description;
    private Set<OssAdminUser> ossAdminUsers;

    // Property accessors
    public String getDepartmentId() {
        return this.departmentId;
    }

    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId;
    }

    public String getDepartmentName() {
        return this.departmentName;
    }

    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    public String getDepartmentParentId() {
        return this.departmentParentId;
    }

    public void setDepartmentParentId(String departmentParentId) {
        this.departmentParentId = departmentParentId;
    }

    public String getDepartmentType() {
        return this.departmentType;
    }

    public void setDepartmentType(String departmentType) {
        this.departmentType = departmentType;
    }

    public String getDepartmentAddress() {
        return this.departmentAddress;
    }

    public void setDepartmentAddress(String departmentAddress) {
        this.departmentAddress = departmentAddress;
    }

    public String getDepartmentContact() {
        return this.departmentContact;
    }

    public void setDepartmentContact(String departmentContact) {
        this.departmentContact = departmentContact;
    }

    public String getDepartmentPhone() {
        return this.departmentPhone;
    }

    public void setDepartmentPhone(String departmentPhone) {
        this.departmentPhone = departmentPhone;
    }

    public String getDepartmentFax() {
        return this.departmentFax;
    }

    public void setDepartmentFax(String departmentFax) {
        this.departmentFax = departmentFax;
    }

    public String getActive() {
        return this.active;
    }

    public void setActive(String active) {
        this.active = active;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set<OssAdminUser> getOssAdminUsers() {
        return ossAdminUsers;
    }

    public void setOssAdminUsers(Set<OssAdminUser> ossAdminUsers) {
        this.ossAdminUsers = ossAdminUsers;
    }
}
