package com.focustech.oss2008.model;

import java.util.Date;

import com.focustech.oss2008.FieldConstants;
import com.focustech.oss2008.annotation.Display;

/**
 * OssAdminProxyusers generated by MyEclipse Persistence Tools
 */
public class OssAdminProxyUser implements java.io.Serializable {
    private static final long serialVersionUID = 7450728184461105463L;
    // Fields
    private Long recordId;
    @Display(FieldConstants.USER_NO_FIELD)
    private String userId;
    @Display(FieldConstants.PROXY_NO_FIELD)
    private String proxyId;
    @Display(FieldConstants.START_TIME_FIELD)
    private Date startTime;
    @Display(FieldConstants.END_TIME_FIELD)
    private Date endTime;
    private String active;
    private String remark;
    private String creatorId;
    private Date createdTime;
    private String modifierId;
    private Date modifierTime;

    // Constructors
    /** default constructor */
    public OssAdminProxyUser() {
    }

    /** full constructor */
    public OssAdminProxyUser(String userId, String proxyId, Date startTime, Date endTime, String creatorId,
            Date createdTime, String modifierId, Date modifierTime) {
        this.userId = userId;
        this.proxyId = proxyId;
        this.startTime = startTime;
        this.endTime = endTime;
        this.creatorId = creatorId;
        this.createdTime = createdTime;
        this.modifierId = modifierId;
        this.modifierTime = modifierTime;
    }

    // Property accessors
    public Long getRecordId() {
        return this.recordId;
    }

    public void setRecordId(Long recordId) {
        this.recordId = recordId;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getProxyId() {
        return this.proxyId;
    }

    public void setProxyId(String proxyId) {
        this.proxyId = proxyId;
    }

    public Date getStartTime() {
        return this.startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return this.endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public String getCreatorId() {
        return this.creatorId;
    }

    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId;
    }

    public Date getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    public String getActive() {
        return active;
    }

    public void setActive(String active) {
        this.active = active;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getModifierId() {
        return modifierId;
    }

    public void setModifierId(String modifierId) {
        this.modifierId = modifierId;
    }

    public Date getModifierTime() {
        return modifierTime;
    }

    public void setModifierTime(Date modifierTime) {
        this.modifierTime = modifierTime;
    }
}
