package com.focustech.oss2008.model;

import java.util.Date;

/**
 * OssAdminLoginLog generated by MyEclipse Persistence Tools
 */
public class OssAdminLoginLog implements java.io.Serializable {
    private static final long serialVersionUID = 7548831024042779600L;
    /** 登陸狀態︰成功 */
    public static final String LOGIN_STATUS_SUCCESS = "1";
    /** 登陸狀態︰失敗 */
    public static final String LOGIN_STATUS_FAILED = "0";
    // Fields
    private Long recordId;
    private String modelName;
    private String loginName;
    private Date loginTime;
    private String loginIp;
    private String remoteName;
    private String loginStatus;
    private String remark;

    // Property accessors
    public Long getRecordId() {
        return this.recordId;
    }

    public void setRecordId(Long recordId) {
        this.recordId = recordId;
    }

    public String getModelName() {
        return this.modelName;
    }

    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    public String getLoginName() {
        return this.loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public Date getLoginTime() {
        return this.loginTime;
    }

    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    public String getLoginIp() {
        return this.loginIp;
    }

    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    public String getRemoteName() {
        return this.remoteName;
    }

    public void setRemoteName(String remoteName) {
        this.remoteName = remoteName;
    }

    public String getLoginStatus() {
        return loginStatus;
    }

    public void setLoginStatus(String loginStatus) {
        this.loginStatus = loginStatus;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }
}
