package com.focustech.oss2008.model;

/**
 * OssAdminLoginControl generated by MyEclipse Persistence Tools
 */
public class OssAdminLoginControl implements java.io.Serializable {
    private static final long serialVersionUID = 6461684009637235582L;
    // Fields
    private String userId;
    private OssAdminUser user;
    private String loginName;
    private String loginIp;

    // Property accessors
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getLoginName() {
        return this.loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public String getLoginIp() {
        return this.loginIp;
    }

    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    public OssAdminUser getUser() {
        return user;
    }

    public void setUser(OssAdminUser user) {
        this.user = user;
    }
}
